language: node_js
node_js:
  - "11"

script: $TEST_COMMAND

env:
  global:
    - USE_SAUCE=false
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
    - TEST_COMMAND="npm test"
    - secure: WSPWhlnC4mWSnSPquX+m1/BCu5ch5NygkaHuM2Nea7lD8oS3XLX8QncZZAsQ4lnNfqoDDuBOizG0AESiqNvE4y6x5qvLLTS6q+ce255ZEMZ71TBdZgDEEvGMEjOPPsVXiXyTQOP1lwOPlrbZvaPgWV7e11KIBab6DfFcQpnvDgo=
    - secure: SW7CJhZnwaNT749Gdnhvqb5rbXlAOsygUAzh9qhtyvbqXKkmJdBIEsO01YF6pbju1X2twE9JvWCOxeZju43NgQChJlPsGbjY2j3k/TdQeTAJesQe2K7ytwghunI30gjEovtRH0T3w1EmcKPH8yj5eBIcB2OYoJHx8KEC7e68q1g=

addons:
  sauce_connect: true

matrix:
  include:
    - env:
      - USE_SAUCE=true
      - TEST_COMMAND="bash travis-core-script.sh"
      - JASMINE_BROWSER="firefox"
      - SAUCE_OS="Linux"
      - SAUCE_BROWSER_VERSION=''
      - USE_SAUCE=true
      - TEST_COMMAND="bash travis-core-script.sh"
      - JASMINE_BROWSER="internet explorer"
      - SAUCE_OS="Windows 8.1"
      - SAUCE_BROWSER_VERSION=11
    - env:
      - USE_SAUCE=true
      - TEST_COMMAND="bash travis-core-script.sh"
      - JASMINE_BROWSER="internet explorer"
      - SAUCE_OS="Windows 8"
      - SAUCE_BROWSER_VERSION=10
